### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by Moorst** [aelvan/craft-imager-do-spaces-driver#2]
Transforms are being uploaded to the DO space with their filename being the full path, e.g;

`C:\xampp\htdocs\example\web\transforms\1762\example_069_772f1b0be8f4b2ebdc0bb5e554103015.jpg`

Whereas, the transform is trying to be referenced at the following; 

`https://example-assets.ams3.digitaloceanspaces.com/transforms//943/example_069_772f1b0be8f4b2ebdc0bb5e554103015.jpg'`

Have I set this up incorrectly? Here is my imager.php config;

```
return [
    'allowUpscale' => false,
    'imagerSystemPath' => '@webroot/transforms',
    'imagerUrl' => 'https://example-assets.ams3.digitaloceanspaces.com/transforms',
    'storages' => ['dospaces'],
    'addVolumeToPath' => false,
    'storageConfig' => [
        'dospaces'  => [
            'endpoint' => 'https://ams3.digitaloceanspaces.com',
            'accessKey' => getenv('SPACES_API_KEY'),
            'secretAccessKey' => getenv('SPACES_SECRET'),
            'region' => getenv('SPACES_REGION'),
            'bucket' => getenv('SPACES_BUCKET'),
            'folder' => 'transforms',
            'requestHeaders' => array(),
        ]
    ]
];
```

**Comment by proimage** [comment]
I'm getting this exact same issue; seeing Windows-style "paths" as filenames in DO. It's probably something to do with backslashes `\` not being considered directory separators in *nix, so they're just getting included in the file name.

**Comment by proimage** [comment]
In case it helps, this is a URL (obviously redacted so it won't work) that was generated by my Windows dev machine uploading Imager-transformed images to a DO Space:

`https://______.nyc3.digitaloceanspaces.com/_____/imager/C:/Users/____/Projects/____/web/imager/thumbnails/test-entry-title/2888/Launching_Thumbnail_W500_H250_Mcrop_Q80_P49-61-34-17_34542f4284.png`

**Comment by proimage** [comment]
*** Bump! ***

**Comment by proimage** [comment]
@aelvan ...

**Comment by proimage** [comment]
Knock knock!

**Comment by aelvan** [comment]
Hi, Imager 2.0 and its companion plugins are no longer supported and have been replaced with Imager X which is a paid plugin.
